field: c1cc181b-5cb9-4d6a-9331-d0892d7a8d26
fieldLayouts:
  8c940db1-37e0-43d3-871d-d07cdf757a8d:
    tabs:
      -
        elements:
          -
            fieldUid: bd03c1ac-10d1-44cd-8323-c29bfd65d40f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  bd03c1ac-10d1-44cd-8323-c29bfd65d40f:
    contentColumnType: text
    fieldGroup: null
    handle: paragraph
    instructions: ''
    name: Paragraph
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: paragraph
name: Paragraph
sortOrder: 2
