field: c1cc181b-5cb9-4d6a-9331-d0892d7a8d26
fieldLayouts:
  c68595fa-c343-4205-ac3b-f2ec8064a68b:
    tabs:
      -
        elements:
          -
            fieldUid: 9f78dd2a-9c45-46aa-89e6-867fa9d8cf38
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4c932ab7-eae0-4d25-bb1a-c0c848964528
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d1e87cb-eacf-4e00-90a6-4dd9f6a666f9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0d1e87cb-eacf-4e00-90a6-4dd9f6a666f9:
    contentColumnType: text
    fieldGroup: null
    handle: tailwindClass
    instructions: ''
    name: 'Tailwind Class'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4c932ab7-eae0-4d25-bb1a-c0c848964528:
    contentColumnType: integer(10)
    fieldGroup: null
    handle: numbeOfPost
    instructions: ''
    name: 'Numbe Of Post'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  9f78dd2a-9c45-46aa-89e6-867fa9d8cf38:
    contentColumnType: text
    fieldGroup: null
    handle: head
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recentPost
name: 'Recent Post'
sortOrder: 3
