fieldLayouts:
  fc0985f4-2152-4faa-9775-9e1822d0cf51:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: soilType
name: 'soil type'
siteSettings:
  e2bac105-6801-4eaf-a11a-5e0c82a9273c:
    hasUrls: true
    template: plants/plant-type
    uriFormat: 'plants?soil-type={slug}'
structure:
  maxLevels: null
  uid: 57227b05-263c-4087-ae86-d42231d1085a
