contentColumnType: text
fieldGroup: 73e40fc9-1289-45d9-9c05-551d9f9fafed
handle: harvest
instructions: 'Time from sowing until... Harvest(months)'
name: Harvest
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: months
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
