contentColumnType: text
fieldGroup: cb72e9ae-6f7a-4d33-927a-22365bdfeb64
handle: species
instructions: 'Plant''s species'
name: Species
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
