contentColumnType: text
fieldGroup: cb72e9ae-6f7a-4d33-927a-22365bdfeb64
handle: variety
instructions: 'Variety of plant'
name: 'Variety '
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: Variety
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
