enableVersioning: false
handle: about
name: about
propagationMethod: all
siteSettings:
  e2bac105-6801-4eaf-a11a-5e0c82a9273c:
    enabledByDefault: true
    hasUrls: true
    template: page/about
    uriFormat: page/about
type: single
