enableVersioning: true
handle: plants
name: Plants
propagationMethod: all
siteSettings:
  e2bac105-6801-4eaf-a11a-5e0c82a9273c:
    enabledByDefault: true
    hasUrls: true
    template: plants/_entry
    uriFormat: 'plants/{slug}'
type: channel
